### ISSUE TITLE
Looks like the Druid version will be stucked in 0.13.0-incubating forever, is this by design?

### ISSUE THREAD

**Issue by didip** [rovio/rovio-ingest#17]
This project relied on `org.apache.druid.segment.realtime.appenderator.SegmentIdentifier` which only exists on 0.13.0-incubating.

Is this by design? Can it be upgraded to Druid `0.22.0`?

**Comment by nsi88** [comment]
Hi guys,
Are there any news about Druid 0.22 support?

**Comment by vivek-balakrishnan-rovio** [comment]
Hi nsi88,

We plan to upgrade Druid version over the summer, no ETA as there are holidays where we work from.
Please note, this fork already has commits to upgrade [Druid to 0.22.1 version](https://github.com/rovio/rovio-ingest/commit/a9437f7dddc6c90a375d45213478929aaa7a5240)

We also welcome pull request if you would like make this change?

Regards,
Vivek

**Comment by nsi88** [comment]
Hi @vivek-balakrishnan-rovio 

Thanks for letting me know.

It would be interesting to make the change. But I'm afraid I won't find time for it. Sorry.

Regards,
Sergey

**Comment by mustafacse** [comment]
@vivek-balakrishnan-rovio is the druid_0.22.1 commit is working ? I tried using that over EMR 6.1.1 but its failing with below exception - 
> ds.repartitionByDruidSegmentSize("date").write.mode(SaveMode.Overwrite).options(options).druid("spark-test", timeColumn="date")
22/07/23 04:52:11 ERROR AsyncEventQueue: Listener EventLoggingListener threw an exception
java.util.ConcurrentModificationException
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1408)
	at scala.collection.convert.Wrappers$JPropertiesWrapper$$anon$6.next(Wrappers.scala:424)
	at scala.collection.convert.Wrappers$JPropertiesWrapper$$anon$6.next(Wrappers.scala:420)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.mutable.MapLike.toSeq(MapLike.scala:75)
	at scala.collection.mutable.MapLike.toSeq$(MapLike.scala:72)
	at scala.collection.mutable.AbstractMap.toSeq(Map.scala:82)
	at org.apache.spark.scheduler.EventLoggingListener.redactProperties(EventLoggingListener.scala:290)
	at org.apache.spark.scheduler.EventLoggingListener.onJobStart(EventLoggingListener.scala:162)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
22/07/23 04:52:12 WARN MetadataUpdater: No segments created, skipping metadata update.

**Comment by mustafacse** [comment]
@vivek-balakrishnan-rovio @juhoautio-rovio 
This is my java version  
java -version
openjdk version "1.8.0_342"
OpenJDK Runtime Environment Corretto-8.342.07.1 (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM Corretto-8.342.07.1 (build 25.342-b07, mixed mode)

Using EMR 6.1.1 Any help would really help

**Comment by vivek-balakrishnan-rovio** [comment]
@[mustafacse](https://github.com/mustafacse) from the stacktrace it seems that the error is related to Mysql not Druid. 
Is this failure from one of the tests ?
Can you please check what version mysql you use and possible try updating the connector.

**Comment by mustafacse** [comment]
I am using 8.0.28 version of mysql connector in Pom file. Which is the
latest.
